// lib/core/kcp_bridge.dart
// KCP Rust FFI bridge — flutter_rust_bridge generated interface.
//
// In production this file is auto-generated by flutter_rust_bridge from
// koda_protocol/src/bridge.rs. The Rust functions are exposed as async Dart
// methods that call into the compiled koda_protocol.so / .dylib / .dll.
//
// During development / demo mode (no compiled Rust library), every call
// falls back to the pure-Dart demo implementation below.
//
// How to generate production bindings:
//   1. flutter_rust_bridge_codegen generate \
//        --rust-input koda_protocol/src/bridge.rs \
//        --dart-output lib/core/kcp_bridge.dart
//   2. cargo build --release -p koda_protocol
//   3. Copy target/release/libkoda_protocol.dll to the Flutter build output dir

import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

// ── Native library availability ───────────────────────────────────────────────
// Set to true by initKcpBridge() if the Rust FFI library loads successfully.
bool _nativeAvailable = false;

/// Call once during app startup (after login). Returns true if native
/// Rust KCP library is available. Falls back to demo mode if not.
Future<bool> initKcpBridge() async {
  try {
    // Production: await RustLib.init(); _nativeAvailable = true;
    _nativeAvailable = false;
  } catch (_) {
    _nativeAvailable = false;
  }
  return _nativeAvailable;
}

// ── Public KCP API ────────────────────────────────────────────────────────────

/// Generate a full X3DH key bundle for this device.
/// Returns public key material to upload to the server.
/// Private keys are stored locally and never transmitted.
Future<KcpKeyBundle> kcpGenerateBundle() async {
  if (_nativeAvailable) {
    // return await RustLib.kcpGenerateBundle();
  }
  return DemoKcp.generateBundle();
}

/// Encrypt [plaintext] using the KCP Double Ratchet for [channelId].
/// Returns the wire payload fields ready for the Phoenix API.
Future<KcpEncrypted> kcpEncrypt({
  required String channelId,
  required String plaintext,
}) async {
  if (_nativeAvailable) {
    // return await RustLib.kcpEncrypt(channelId: channelId, plaintext: plaintext);
  }
  return DemoKcp.encrypt(channelId, plaintext);
}

/// Decrypt a received KCP payload for [channelId].
/// Returns the plaintext string.
Future<String> kcpDecrypt({
  required String channelId,
  required String payload,
  required String ratchetKey,
  required int    msgNumber,
  required int    prevChain,
  required String nonce,
}) async {
  if (_nativeAvailable) {
    // return await RustLib.kcpDecrypt(...);
  }
  return DemoKcp.decrypt(payload);
}

/// Rotate the signed pre-key. Should be called every 7 days.
Future<KcpSpkRotation> kcpRotateSpk() async {
  if (_nativeAvailable) {
    // return await RustLib.kcpRotateSpk();
  }
  return DemoKcp.rotateSpk();
}

/// Whether the native Rust library is loaded and real crypto is active.
bool get kcpIsNative => _nativeAvailable;

// ── Data types ────────────────────────────────────────────────────────────────

class KcpKeyBundle {
  final String ikSignPub;    // Ed25519 identity signing key (public)
  final String ikDhPub;      // X25519 identity DH key (public)
  final String spkPub;       // Signed pre-key (public)
  final String spkSig;       // Signature over spkPub by ikSignPub
  final List<String> opks;   // One-time pre-keys (public)

  const KcpKeyBundle({
    required this.ikSignPub,
    required this.ikDhPub,
    required this.spkPub,
    required this.spkSig,
    required this.opks,
  });

  Map<String, dynamic> toJson() => {
    'ik_sign_pub': ikSignPub,
    'ik_dh_pub':   ikDhPub,
    'spk_pub':     spkPub,
    'spk_sig':     spkSig,
    'opks':        opks,
  };

  factory KcpKeyBundle.fromJson(Map<String, dynamic> j) => KcpKeyBundle(
    ikSignPub: j['ik_sign_pub'] as String,
    ikDhPub:   j['ik_dh_pub']   as String,
    spkPub:    j['spk_pub']     as String,
    spkSig:    j['spk_sig']     as String,
    opks:      List<String>.from(j['opks'] as List? ?? []),
  );
}

class KcpEncrypted {
  final String payload;      // base64 ciphertext
  final String ratchetKey;   // base64 ratchet public key
  final int    msgNumber;
  final int    prevChain;
  final String nonce;        // base64 12-byte nonce

  const KcpEncrypted({
    required this.payload,
    required this.ratchetKey,
    required this.msgNumber,
    required this.prevChain,
    required this.nonce,
  });

  Map<String, dynamic> toJson() => {
    'payload':     payload,
    'ratchet_key': ratchetKey,
    'msg_number':  msgNumber,
    'prev_chain':  prevChain,
    'nonce':       nonce,
  };
}

class KcpSpkRotation {
  final String newSpkPub;
  final String newSpkSig;
  const KcpSpkRotation({required this.newSpkPub, required this.newSpkSig});
}

// ── Demo KCP (pure Dart, no real encryption) ──────────────────────────────────
// Used when the native Rust library is not available.
// "Encryption" is UTF-8 → base64. Wire format is correct; crypto is not.
// NEVER use in production with real user data beyond Alpha testing.
class DemoKcp {
  DemoKcp._();

  static final _rng = Random.secure();

  static String _randomBase64(int bytes) {
    final buf = Uint8List(bytes);
    for (var i = 0; i < bytes; i++) buf[i] = _rng.nextInt(256);
    return base64Encode(buf);
  }

  static KcpKeyBundle generateBundle() => KcpKeyBundle(
    ikSignPub: _randomBase64(32),
    ikDhPub:   _randomBase64(32),
    spkPub:    _randomBase64(32),
    spkSig:    _randomBase64(64),
    opks:      List.generate(20, (_) => _randomBase64(32)),
  );

  static KcpEncrypted encrypt(String channelId, String plaintext) {
    // Demo "encryption": UTF-8 → base64
    final payload = base64Encode(utf8.encode(plaintext));
    return KcpEncrypted(
      payload:    payload,
      ratchetKey: _randomBase64(32),
      msgNumber:  0,
      prevChain:  0,
      nonce:      _randomBase64(12),
    );
  }

  static String decrypt(String payload) {
    try {
      // Pad base64 if needed
      final padded = payload.padRight(
          (payload.length + 3) ~/ 4 * 4, '=');
      return utf8.decode(base64Decode(padded));
    } catch (_) {
      // If decryption fails, return payload as-is (plain text fallback)
      return payload;
    }
  }

  static KcpSpkRotation rotateSpk() => KcpSpkRotation(
    newSpkPub: _randomBase64(32),
    newSpkSig: _randomBase64(64),
  );
}